[[media]]
title = "Dr. STONE SCIENCE FUTURE Cour 3"
type = "anime"
submitters = ["SubsPlease"]
search_name = "Dr. STONE s4"

[[media]]
title = "Classroom of the Elite 4th Season: Second Year, First Semester"
type = "anime"
submitters = ["SubsPlease"]
search_name = "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e S4"

[[media]]
title = "Welcome to Demon School! Iruma-kun Season 4"
type = "anime"
submitters = ["SubsPlease"]
search_name = "Mairimashita! Iruma-kun S4"

[[media]]
title = "MARRIAGETOXIN"
type = "anime"
submitters = ["SubsPlease"]

[[media]]
title = "Witch Hat Atelier"
type = "anime"
submitters = ["Erai-raws"]
search_name = "Tongari Boushi no Atelier"

[[media]]
title = "That Time I Got Reincarnated as a Slime Season 4"
type = "anime"
submitters = ["Erai-raws"]
search_name = "Tensei Shitara Slime Datta Ken 4"

[[media]]
title = "Ascendance of a Bookworm: Adopted Daughter of an Archduke"
type = "anime"
submitters = ["SubsPlease"]
search_name = "Honzuki no Gekokujou S4"

[[media]]
title = "Reborn as a Vending Machine, I Now Wander the Dungeon Season 3"
type = "anime"
submitters = ["SubsPlease"]
search_name = "Jidou Hanbaiki ni Umarekawatta Ore wa Meikyuu wo Samayou S3"
